### ISSUE TITLE
de.mkammerer.grpcchat 这些包在哪里下载啊

### ISSUE THREAD

**Issue by coyool** [Jacksgong/grpc-android-kotlin#1]
import de.mkammerer.grpcchat.protocol.Error
import de.mkammerer.grpcchat.protocol.RoomMessage

**Comment by Jacksgong** [comment]
不用下载，参考文档的第三步: [3-运行android端](https://github.com/Jacksgong/grpc-android-kotlin/blob/master/README-zh.md#3-运行android端)  -- `bash refresh-android-proto.sh`
